# Book settings
title: 3D Game Engine Programming
author: 3dgep
logo: images/favicon.png

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Define the name of the latex output file
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/3dgep/3dgep.github.io
  path_to_book: .
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  favicon: images/favicon.png
  extra_navbar: ""
  home_page_in_navbar: false

# Sphinx configuration
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/3dgep/3dgep.github.io
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: false
      home_page_in_toc: true
